# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mockinator.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import CustomTextEdit

class Ui_mw(object):
    def setupUi(self, mw):
        mw.setObjectName("mw")
        mw.resize(838, 623)
        self.centralwidget = QtWidgets.QWidget(mw)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cbFilePath = QtWidgets.QComboBox(self.centralwidget)
        self.cbFilePath.setObjectName("cbFilePath")
        self.horizontalLayout.addWidget(self.cbFilePath)
        self.pbOpenFile = QtWidgets.QPushButton(self.centralwidget)
        self.pbOpenFile.setObjectName("pbOpenFile")
        self.horizontalLayout.addWidget(self.pbOpenFile)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.teInputCode = CustomTextEdit.DropableTextEdit(self.centralwidget)
        self.teInputCode.setAcceptDrops(True)
        self.teInputCode.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.teInputCode.setObjectName("teInputCode")
        self.verticalLayout.addWidget(self.teInputCode)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.pbRunMocker = QtWidgets.QPushButton(self.centralwidget)
        self.pbRunMocker.setObjectName("pbRunMocker")
        self.horizontalLayout_4.addWidget(self.pbRunMocker)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabOutputCodeTab = QtWidgets.QTabWidget(self.centralwidget)
        self.tabOutputCodeTab.setObjectName("tabOutputCodeTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.tab)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_4.addWidget(self.lineEdit)
        self.teOutputHeader = QtWidgets.QTextEdit(self.tab)
        self.teOutputHeader.setAcceptDrops(False)
        self.teOutputHeader.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.teOutputHeader.setObjectName("teOutputHeader")
        self.verticalLayout_4.addWidget(self.teOutputHeader)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.pbSave = QtWidgets.QPushButton(self.tab)
        self.pbSave.setObjectName("pbSave")
        self.horizontalLayout_5.addWidget(self.pbSave)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.tabOutputCodeTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.teOutputImpl = QtWidgets.QTextEdit(self.tab_2)
        self.teOutputImpl.setAcceptDrops(False)
        self.teOutputImpl.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.teOutputImpl.setObjectName("teOutputImpl")
        self.verticalLayout_3.addWidget(self.teOutputImpl)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.tabOutputCodeTab.addTab(self.tab_2, "")
        self.verticalLayout_2.addWidget(self.tabOutputCodeTab)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        mw.setCentralWidget(self.centralwidget)
        self.mb = QtWidgets.QMenuBar(mw)
        self.mb.setGeometry(QtCore.QRect(0, 0, 838, 22))
        self.mb.setObjectName("mb")
        mw.setMenuBar(self.mb)
        self.sb = QtWidgets.QStatusBar(mw)
        self.sb.setObjectName("sb")
        mw.setStatusBar(self.sb)

        self.retranslateUi(mw)
        self.tabOutputCodeTab.setCurrentIndex(1)
        self.pbSave.clicked.connect(mw.onSave)
        self.pbRunMocker.clicked.connect(mw.onMockMe)
        self.pbOpenFile.clicked.connect(mw.onOpenFile)
        QtCore.QMetaObject.connectSlotsByName(mw)

    def retranslateUi(self, mw):
        _translate = QtCore.QCoreApplication.translate
        mw.setWindowTitle(_translate("mw", "Mockinator V0.1"))
        self.pbOpenFile.setText(_translate("mw", "Open File"))
        self.pbRunMocker.setText(_translate("mw", "Mock Me!"))
        self.pbSave.setText(_translate("mw", "Save"))
        self.tabOutputCodeTab.setTabText(self.tabOutputCodeTab.indexOf(self.tab), _translate("mw", "Header"))
        self.tabOutputCodeTab.setTabText(self.tabOutputCodeTab.indexOf(self.tab_2), _translate("mw", "Implementation"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw = QtWidgets.QMainWindow()
    ui = Ui_mw()
    ui.setupUi(mw)
    mw.show()
    sys.exit(app.exec_())
